### PR TITLE
Article about new menu

### PR DESCRIPTION
**Pull request by marmarta**
Tiny and brief introduction to new qubes app menu

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Looks good. Thanks for writing this, @marmarta! :slightly_smiling_face:

If I understand correctly, @ninavizz has offered some content feedback on this article, which @marmarta is currently reviewing and deciding whether/how to make further content revisions in response to the feedback. So, I'll hold off on my copy-editing pass until the substantive content changes are done. Please let me know when ready, @marmarta.

**Comment by andrewdavidwong** [comment]
Note to self: https://github.com/QubesOS/qubes-attachment/pull/52

**Comment by marmarta** [comment]
@andrewdavidwong , changes from @ninavizz incorporated, this is ready (barring a single missing link to a new survey that's being made by @ninavizz )

**Comment by ninavizz** [comment]
Survey link! https://survey.qubes-os.org/index.php?r=survey/index&sid=255277&lang=en

**Comment by ninavizz** [comment]
(apologies for the designer that cannot figure out github)

Suggested edit to text in the last section:

As this is very much a first release, bugs are likely. For bugs, please [file any issues in GitHub](https://github.com/QubesOS/qubes-issues/issues).

We will also be continuing to refine the design and add features to the menu, as we are able to (and as contribuor PRs come in). With informing both, we'd love your [feedback via an anonymous/private survey](https://survey.qubes-os.org/index.php?r=survey/index&sid=255277&lang=en). We are also active in the [forum](https://forum.qubes-os.org/) and welcome discussion, there. 

To see the features we already have in mind for the future, see [our project on GitHub for the new Application Menu](https://github.com/QubesOS/qubes-issues/projects/12). Don't see something there that you'd like to see? Go ahead and [create a new issue](https://github.com/QubesOS/qubes-issues/issues), or strike up a discussion in the forum.

**Comment by marmarta** [comment]
I've added some parts of the edit. This is ready for review now.

**Comment by andrewdavidwong** [comment]
Edits pushed. @marmarta, please have a look at your convenience and let me know if you're ok with these changes.

**Comment by marmarta** [comment]
Looks good to me :)

**Pull request merged**
