### PR TITLE
Republish 3mdeb's TrenchBoot AEM post

### PR DESCRIPTION
**Pull request by andrewdavidwong**
Original: https://github.com/3mdeb/news-and-ideas/pull/503

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
TestDeploy

**Comment by miczyg1** [comment]
@andrewdavidwong could you please cherry-pick this commit as well? https://github.com/3mdeb/news-and-ideas/pull/509/commits/59bfa2211b37983b8fd205cb6135c3a114341e1a

**Comment by macpijan** [comment]
@miczyg1 @andrewdavidwong Created  PR with udpated content here: https://github.com/QubesOS/qubes-posts/pull/104

**Comment by andrewdavidwong** [comment]
@miczyg1 @macpijan: What about https://github.com/3mdeb/news-and-ideas/pull/503/commits/8ee43219a2bc2539a73926950b082d4c078f79e1?

**Comment by andrewdavidwong** [comment]
Never mind. I see now that your PR already includes it.

**Comment by macpijan** [comment]
> Never mind. I see now that your PR already includes it.

Correct. Thanks.

**Pull request merged**
