### PR TITLE
Survey post

### PR DESCRIPTION
**Pull request by marmarta**
Depends on https://github.com/QubesOS/qubes-attachment/pull/38

### CODE REVIEW

**Comment by marmarta** [comment]
@andrewdavidwong , as per email, this is the ready PR :) 
@marmarek is going to use this to try and debug the gitlab CI pipeline, so if you notice weird debug strings, please ignore them.

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by andrewdavidwong** [comment]
Fantastic post, @marmarta. :slightly_smiling_face:  I've pushed some copyediting revisions. Please feel free to accept or reject any of them, and let me know if you have any questions.

**Comment by marmarta** [comment]
> Fantastic post, @marmarta. slightly_smiling_face I've pushed some copyediting revisions. Please feel free to accept or reject any of them, and let me know if you have any questions.

Thank you very much! I accept all changes, they look very good - thank you for editing :)

**Review by marmarek — APPROVED** [review]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of f7b602c6ac75fc12809883363c4dc5f61c743175
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAl/G6F8ACgkQ8yiUvpaE
k4psfRAAqpOEkvvhnXTy43c+VnRpXtYohtngLhkbQvbC2tFRpQvSuEjBmi3EZPB9
+3ce7UzPwa9bmRjLGU6ZC7Q/tSbnxwqv+uTNmi0Taazdy9Rnh7mIw5ILeMcVVK0C
MPWH5cFZpSE1HNYDUB0ioFax/I2Smbo/+srl6TeIgBawhMJc+IddwN7q4D7lOFb0
/spHmlxkbZjTNpmHc7RzJypWilUzFjf5bgnwpQd7i8m56eqdw+g4N+gGS1hX5ex+
pqam1b1RLw+b6JB+XTa02vxVj2lgMJsoZd+pmpXnw6WvNwFBn+i+djRSm9B/1e6W
PunNbey3di7cH7KudP7cfValDQ1CJcEh4MhMw770IVpSQtnDNH/uF0Ga7Lb4Ruza
lIDIkktRt1zNZlyz2gYzBgE3DgItMnOPlL4AqGsw42BrClJ2IQubdhWFf/la1fdt
Re6dCEHfr0y12VTXI1lcfqS5Rogf8V/SDN7NWpT8rcosE6vgQ2k4U2uAVtotoZ9W
8hobbGWA5iey5paNvXklMkEGjO24J9+qxsI1cBXzqTiW/wsBMQ/NRHTb/wXRLGJW
jQYx7e77rX9DkexrsvIC8cBu7P6HiRHsXVzxtIJLUKL/woqA0hfNt2JC7nQxCwcP
QS37ewqs3gR7t5ioF8XYUEF+JldYgHGJGREXw5GWUFgdiCwD5Bg=
=kck2
-----END PGP SIGNATURE-----
```

**Pull request merged**
