### PR TITLE
Announcement: Whonix 17 templates available for Qubes OS 4.1

### PR DESCRIPTION
**Pull request by andrewdavidwong**
@adrelanos, please review also.

### CODE REVIEW

**Comment by adrelanos** [comment]
Looks excellent as is! Thank you!

**Comment by marmarek** [comment]
The announcement looks okay, but the templates (and salt formulas) are still in testing repository, I guess we should wait until they are moved to stable, right?
I'll run another test round over the weekend (this time including fresh install too), so I guess they should be ready to move on Monday, if @adrelanos is okay with that.

**Comment by adrelanos** [comment]
Yes, sounds good.

**Comment by marmarek** [comment]
Further testing shows that sys-whonix based on Whonix 17 doesn't work as updatevm on R4.1 (R4.2 is not affected). This is an upstream Debian bug. More details at https://github.com/QubesOS/qubes-issues/issues/8482#issuecomment-1902781778 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1061258.
At this point, I think it should be noted in the announcement (unless we want to wait for the bug to be fixed first? IMO not a great idea). Possible workarounds:
 - use sys-firewall as updatevm (but then dom0 updates will happen over clearnet)
 - create separate updatevm based on Fedora (sys-update?) and set its netvm to sys-whonix. To create updatevm, create an app qube on a fedora template (or debian-11 which also isn't affected by the issue), then enable `qubes-updates-proxy` service in the "services" tab in qubes settings (available in drop-down), and finally set this qubes as "updatevm" in global settings.

**Comment by marmarek** [comment]
> unless we want to wait for the bug to be fixed first? IMO not a great idea

I just got a notification the bug is fixed! But then, I'm not sure about the process to reach it Debian stable, for now it looks to be uploaded just to Debian unstable. @adrelanos do you know how long it will take it to migrate to stable?

**Comment by adrelanos** [comment]
> @adrelanos do you know how long it will take it to migrate to stable?

Not really. What I could find about Debian point release cycle here: https://wiki.debian.org/DebianReleases/PointReleases

> As of February 2009 they should happen about every two months.

As per https://lists.debian.org/debian-announce/2023/msg00005.html

> Debian 12.3 image release delayed

On 9 December 2023.

So in theory, Debian 12.4 might be released on 09 February 2024 but that's highly speculative.

//cc @h01ger any idea?

> use sys-firewall as updatevm (but then dom0 updates will happen over clearnet)

Please don't update Whonix Templates over clearnet. That would break the "the everything Tor OS" project goal.

> create separate updatevm based on Fedora (sys-update?) and set its netvm to sys-whonix. To create updatevm, create an app qube on a fedora template (or debian-11 which also isn't affected by the issue), then enable qubes-updates-proxy service in the "services" tab in qubes settings (available in drop-down), and finally set this qubes as "updatevm" in global settings.

Sounds quite complex, error-prone but that seems better.

----

Yet another workaround not sure how hard on your side:
Take the fixed Debian upstream package and upload to Qubes Debian repository. That way you would front-run the Debian stable point release and wouldn't need to wait for it.

That however seems much easier than above workaround.

**Comment by marmarek** [comment]
> Please don't update Whonix Templates over clearnet. That would break the "the everything Tor OS" project goal.

That's another thing. I meant updatevm for dom0 updates.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
>> Please don't update Whonix Templates over clearnet. That would break the "the everything Tor OS" project goal.
> 
> That's another thing. I meant updatevm for dom0 updates.

Ok. Then this is much less of an issue. That workaround that users could 
manually apply is sufficient as long as there's no unexpected 
non-torified (fail open) connections for users that previously set dom0 
UpdateVM to sys-whonix.

OK solutions:

* user can manually apply workaround
* Qubes salt automated workaround
* waiting for Debian point release
* uploading the fixed package to Qubes Debian repository

**Comment by marmarek** [comment]
> * uploading the fixed package to Qubes Debian repository

Looking into it right now.

**Comment by marmarek** [comment]
Another issue found in testing: https://github.com/Kicksecure/tb-updater/issues/27

**Comment by adrelanos** [comment]
> Another issue found in testing: [Kicksecure/tb-updater#27](https://github.com/Kicksecure/tb-updater/issues/27)

Confirmed fixed. (https://github.com/Kicksecure/tb-updater/issues/27#issuecomment-1925246048)

**Comment by marmarek** [comment]
> @marmarek, should I publish this now?

Yes, I just pushed the templates to stable repo, good to publish.

**Pull request merged**
